Repository chwerth/RAstral_Rampart, pull requests merged in 2020-05, with the labels that each got.

#19 Added some documentation!
  SpinnyGun.py
  spinny_gun.py
Labels: documentation

#24 Added some math to make projectile draw at nose
  spinny_gun.py
Labels: bug

#34 added bg music and sfx for shooting + explosions
  CREDITS.txt
  assets/audio/bensound-endlessmotion.mp3
  assets/audio/explosion.wav
  assets/audio/laser.wav
  spinny_gun.py
Labels: enhancement

#44 Player()
  spinny_gun.py
Labels: enhancement

#48 finalized setup.py file
  setup.py
Labels: enhancement

#52 Game over screen
  spinny_gun.py
Labels: enhancement

#53 added score display funcitonality + formatting
  spinny_gun.py
Labels: enhancement

#69 animated flying missiles
  main.py
Labels: Essential

#77 developed Hud object
  game_loop.py
  hud.py
Labels: Essential
